name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # runs daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write  # needed to push generated files

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Light Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: jjijon7000
          color: 1e3c72  # blue gradient
          output: dist/github-contribution-grid-snake.svg

      - name: Generate Dark Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: jjijon7000
          color: ffffff  # white color for dark background
          output: dist/github-contribution-grid-snake-dark.svg

      - name: Push generated SVGs
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          directory: dist
